version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: always
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "8011:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
