<?php


namespace Tests\App\Reports;


use App\Report\AvgPostsCountPerUserPerMonthReport;
use App\Repository\InMemoryPostRepository;
use Framework\Cache\InMemoryCache;
use Tests\TestCase;

class AvgPostsCountPerUserPerMonthReportTest extends TestCase
{

    private array $posts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->posts = $this->getDummyPosts(2);
    }

    /**
     * @throws \Exception
     */
    public function testGenerate()
    {
        $report = new AvgPostsCountPerUserPerMonthReport(new InMemoryPostRepository($this->posts), new InMemoryCache());
        $result = $report->generate();

        $res1 = new \StdClass();
        $res1->user_id = '1';
        $res1->user_name = 'user 1';
        $res1->count = 1;

        $res2 = new \StdClass();
        $res2->user_id = '2';
        $res2->user_name = 'user 2';
        $res2->count = 1;

        self::assertEquals([$res1, $res2], $result);
    }
}
