<?php

namespace Tests\App\Reports;

use App\Report\LongestPostPerMonthReport;
use App\Repository\InMemoryPostRepository;
use Framework\Cache\InMemoryCache;
use Tests\TestCase;

class LongestPostPerMonthReportTest extends TestCase
{

    private array $posts;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->posts = $this->getDummyPosts(10);
    }

    public function testGenerate()
    {
        $report = new LongestPostPerMonthReport(new InMemoryPostRepository($this->posts), new InMemoryCache());
        $result = $report->generate();

        $expected = [
            'Jan' => 4,
            'Feb' => 0,
            'Mar' => 0,
            'Apr' => 0,
            'May' => 0,
            'Jun' => 0,
            'Jul' => 0,
            'Aug' => 0,
            'Sep' => 0,
            'Oct' => 0,
            'Nov' => 0,
            'Dec' => 0,
        ];

        self::assertEquals($expected, $result);
    }
}
